apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-strefa
  labels:
    app: httpd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: http
        image: httpd:latest
        ports:
        - containerPort: 80