apiVersion: apps/v1
kind: Deployment
metadata: 
  name: strefa-kursow-deploy
  labels:
    app: app-httpd
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app-httpd
  template:
    metadata:
      labels:
        app: app-httpd
    spec:
      containers:
      - name: strefa-httpd-deploy
        image: httpd:latest
        ports:
        - containerPort: 80
        
# kubectl set image deployment "nazwa_deploy"=httpd:2.4 --record=true (aby zmiany byly widoczne w describe)
# kubectl rolling undo deployment "nazwa_deploy" (cofanie do poprzedniego deployu)
# kubectl rolling history deployment "nazwa_deploy" (historia zmian deployu)
# kubectl rolling status deployment "nazwa_deploy"  (status aktualnego deployu)
# kubectl scale --replicas="ilosc replik" deployment "nazwa_deploy" (skalowanie deploymentu)