apiVersion: batch/v1
kind: Job
metadata: 
  name: strefakursow-odliczanie
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: odliczanie
    spec:
      containers:
      - name: container-odliczanie
        image: centos:7
        command:
        - "bin/bash"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
