apiVersion: v1 #wersja API
kind: Pod #co chcemy uruchomić
metadata:
  name: nginx #nazwa Pod'a
spec: # co chcemy zrobic
  containers:  # chcemy kontener wiec lista opisuje 
  - name: strefa-nginx-container
    image: nginx:1.17