apiVersion: v1
kind: Pod
metadata:
  name: database-vol
spec:
  containers:
  - name: strefa-db-vol
    image: mysql
    volumeMounts:
    - name: dbconnection
      mountPath: /root/secrets
      readOnly: true
    env: 
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
         name: strefa-secret
         key: pass
  volumes:
  - name: dbconnection
    secret:
      secretName: strefa-secret